### ISSUE TITLE
Country filter

### ISSUE THREAD

**Issue by extragornax** [IDerr/jobtracker#1]
An already install country filter maybe

**Comment by skyforce77** [comment]
It is already possible to filter by location using the lua filtering option (but that's a bit tricky)

[Here are the available attributes of the job object](https://github.com/skyforce77/jobtracker/blob/7b983860db221149edeee20b6cb966126e8f0fe5/providers/provider.go#L199)

[And an example is available right here](https://github.com/skyforce77/jobtracker/tree/7b983860db221149edeee20b6cb966126e8f0fe5#filtering)

**Comment by skyforce77** [comment]
You can also use javascript using [jobtracker-js](https://github.com/skyforce77/jobtracker-js)
